receivers:
  hostmetrics:
    collection_interval: 5s
    scrapers:
      cpu:
      memory:
  hostmetrics/disk:
    collection_interval: 10s
    scrapers:
      disk:
      filesystem:

processors:
  batch:
  resourcedetection/system:
    detectors: [env, system]
    override: true

exporters:
  otlp:
    endpoint: otel-collector:4317
    insecure: true
  logging:
    loglevel: debug

service:
  pipelines:
    metrics:
      receivers: [hostmetrics, hostmetrics/disk]
      processors: [resourcedetection/system, batch]
      exporters: [otlp, logging]
