extensions:
  host_observer:

receivers:
  receiver_creator:
    watch_observers: [host_observer]
    receivers:
      dotnet_diagnostics:
        rule: type == "hostport" && process_name == "dotnet"
        config:
          pid: "`process_id`"
  dotnet_diagnostics:
    pid: 3700

processors:
  batch:
  resourcedetection/system:
    detectors: [env, system]
    override: true

exporters:
  otlp:
    endpoint: otel-collector:4317
  logging:
    loglevel: debug

service:
  extensions: [host_observer]
  pipelines:
    metrics:
      # receivers: [receiver_creator]
      receivers: [dotnet_diagnostics]
      processors: [resourcedetection/system, batch]
      exporters: [otlp, logging]
