version: "2"
services:

  # Jaeger
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686" # this is how we see the Jaeger UI - if no mapping, we can't get to it - the mapping allows our machine to 'talk' to the docker 'machines' - exposes them to our machine
      - "14268"
      - "14250"

  # Collector
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.46.0
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317"        # OTLP gRPC receiver
    depends_on:
      - jaeger-all-in-one