version: '3'
services:
  appathon-dotnet:
    build: ./dotnet
    ports:
      - "8080:80"
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: https://otlp.nr-data.net:4317
      OTEL_EXPORTER_OTLP_HEADERS: "api-key=${NEW_RELIC_API_KEY}"
  appathon-java:
    build: ./java
    ports:
      - "8081:8080"
    environment:
      OTEL_SERVICE_NAME: "appathon-java"
      OTEL_RESOURCE_ATTRIBUTES: service.instance.id=6d1331ab-cfd3-4fff-9dfe-21e5cbfab49a
      OTEL_EXPORTER_OTLP_ENDPOINT: https://otlp.nr-data.net:4317
      OTEL_EXPORTER_OTLP_HEADERS: "api-key=${NEW_RELIC_API_KEY}"
      OTEL_EXPORTER_OTLP_COMPRESSION: gzip
      OTEL_METRICS_EXPORTER: otlp
      OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY: DELTA
      OTEL_SPAN_ATTRIBUTE_VALUE_LENGTH_LIMIT: 1000
